//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XinYu.Framework.Library.Implement.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XinYu.Framework.Library.Implement.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 A Cache item don&apos;t has absolute expiration and sliding expiration as the same time. 的本地化字符串。
        /// </summary>
        internal static string CacheHasAbsoluteAndSlidingExpirationAtSameTime {
            get {
                return ResourceManager.GetString("CacheHasAbsoluteAndSlidingExpirationAtSameTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 详细信息: 的本地化字符串。
        /// </summary>
        internal static string EventLogger_MessageDetail {
            get {
                return ResourceManager.GetString("EventLogger_MessageDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志消息不能为空 的本地化字符串。
        /// </summary>
        internal static string EventLogger_MessageNull {
            get {
                return ResourceManager.GetString("EventLogger_MessageNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value must be greater than 0 bytes. 的本地化字符串。
        /// </summary>
        internal static string ExceptionByteArrayValueMustBeGreaterThanZeroBytes {
            get {
                return ResourceManager.GetString("ExceptionByteArrayValueMustBeGreaterThanZeroBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type must be of type HashAlgorithm. 的本地化字符串。
        /// </summary>
        internal static string ExceptionCreatingHashAlgorithmInstance {
            get {
                return ResourceManager.GetString("ExceptionCreatingHashAlgorithmInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type must be of type SymmetricAlgorithm. 的本地化字符串。
        /// </summary>
        internal static string ExceptionCreatingSymmetricAlgorithmInstance {
            get {
                return ResourceManager.GetString("ExceptionCreatingSymmetricAlgorithmInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to decrypt data. 的本地化字符串。
        /// </summary>
        internal static string ExceptionDecrypting {
            get {
                return ResourceManager.GetString("ExceptionDecrypting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常所关联的帮助文件 的本地化字符串。
        /// </summary>
        internal static string ExceptionLogging_HelpLink {
            get {
                return ResourceManager.GetString("ExceptionLogging_HelpLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导致当前异常的 Exception 实例 的本地化字符串。
        /// </summary>
        internal static string ExceptionLogging_InnerException {
            get {
                return ResourceManager.GetString("ExceptionLogging_InnerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导致错误的程序或对象的名 的本地化字符串。
        /// </summary>
        internal static string ExceptionLogging_Source {
            get {
                return ResourceManager.GetString("ExceptionLogging_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 堆栈上的帧字符串 的本地化字符串。
        /// </summary>
        internal static string ExceptionLogging_StackTrace {
            get {
                return ResourceManager.GetString("ExceptionLogging_StackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 引发当前异常的方法 的本地化字符串。
        /// </summary>
        internal static string ExceptionLogging_TargetSite {
            get {
                return ResourceManager.GetString("ExceptionLogging_TargetSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value can not be a null or empty string. 的本地化字符串。
        /// </summary>
        internal static string ExceptionNullOrEmptyString {
            get {
                return ResourceManager.GetString("ExceptionNullOrEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Enumeration Value! 的本地化字符串。
        /// </summary>
        internal static string InvalidEnumerationValue {
            get {
                return ResourceManager.GetString("InvalidEnumerationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 String must represent a valid hexadecimal (e.g. : 0F99DD) 的本地化字符串。
        /// </summary>
        internal static string InvalidHexString {
            get {
                return ResourceManager.GetString("InvalidHexString", resourceCulture);
            }
        }
    }
}
